### ISSUE TITLE
make build fails on llvmlite

### ISSUE THREAD

**Issue by maacl** [metasoarous/analysis#1]
make build fails for me with the below. I am on Ubuntu Ubuntu 20.04 LTS.

```
Building wheels for collected packages: umap-learn, numba, llvmlite
  Running setup.py bdist_wheel for umap-learn: started
  Running setup.py bdist_wheel for umap-learn: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/7d/1d/03/34aade9a9b97acddb8e93654eb856dadbf0964406eef8b96e2
  Running setup.py bdist_wheel for numba: started
  Running setup.py bdist_wheel for numba: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/b1/09/9e/a433f1d8f4390a1e1202880bcd011bb9023f3bd2400a44be51
  Running setup.py bdist_wheel for llvmlite: started
  Running setup.py bdist_wheel for llvmlite: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9885o7j5/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-0hp8z9iq --python-tag cp37:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-9885o7j5/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built umap-learn numba
Failed to build llvmlite
Installing collected packages: llvmlite, numba, umap-learn
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9885o7j5/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2r45bb1e/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-9885o7j5/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-9885o7j5/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-9885o7j5/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9885o7j5/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2r45bb1e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-9885o7j5/llvmlite/
The command '/bin/sh -c pip3 install seaborn &&    pip3 install matplotlib &&    pip3 install sklearn &&    pip3 install numpy &&    pip3 install umap-learn &&    pip3 install trimap &&    pip3 install altair &&    pip3 install jupyter' returned a non-zero code: 1
make: *** [Makefile:40: build] Error 1

```

**Comment by metasoarous** [comment]
Hi @maacl! Thanks so much for kicking the tires and reporting back here!

Very strange that you're having this issue. I'm on an Ubuntu 20.04 fork (Pop!_OS) as well, and its not clear why this would be happening in the docker image anyway, since the external environment shouldn't matter so much. The only think I can think of is if you are running on different hardware, there might be an issue with some binary that is making assumptions about processor (etc) architecture. Would you mind sharing a bit more system/hardware information? Do you have any other machines you'd be able to test on?

I can try running this on another couple of machines here to see if I can't reproduce anything like this.

Again, thank you!

**Comment by maacl** [comment]
Sure thing. Are there any specific commands I can run that would produce the information you need.

**Comment by metasoarous** [comment]
Hey @maacl; I just realized that you posted this issue in this fork of the code. This was created accidentally, and I'll be deleting it. I'm going to repost over at https://github.com/pol-is/analysis.

**Comment by metasoarous** [comment]
Actually @maacl, would you please start by cloning and running the instructions from https://github.com/pol-is/analysis and reopening the issue there if you're still having the problem? That may have been the reason this didn't work.

If you're still having problems, you can get pcu info with

```
cat /proc/cpuinfo
```

Thanks!
